language: go
go:
- '1.11'
sudo: required
script:
- go test -v ./...
- go build -o ssManager .
before_install:
- openssl aes-256-cbc -K $encrypted_58e6f98fc3db_key -iv $encrypted_58e6f98fc3db_iv
  -in deploy.sh.enc -out deploy.sh -d
before_deploy:
- sudo apt-get install sshpass
deploy:
- provider: script
  script: bash deploy.sh
  skip_cleanup: true
  on:
    branch: master
